### ISSUE TITLE
Job hangs on ContainerCreating if volume specified twice

### ISSUE THREAD

**Issue by dleehr** [dleehr/calrissian#2]
A single volume may be mounted twice, but listing the volume itself twice causes the container to hang.

Succeeds:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: single-mount-twice
spec:
  template:
    spec:
      containers:
      - args: [date > /mount-double/double.txt]
        command: [/bin/sh, -c]
        image: debian:stretch-slim
        name: single-mount-twice
        volumeMounts:
        - {mountPath: /mount-single, name: mount-single, subPath: mount-single}
        - {mountPath: /mount-double, name: mount-single, subPath: mount-double}
      restartPolicy: Never
      volumes:
      - name: mount-single
        persistentVolumeClaim:
          claimName: multimount
```

Fails:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: double-mount
spec:
  template:
    spec:
      containers:
      - args: [date > /mount-double/double.txt]
        command: [/bin/sh, -c]
        image: debian:stretch-slim
        name: double-mount
        volumeMounts:
        - {mountPath: /mount-single, name: mount-single, subPath: mount-single}
        - {mountPath: /mount-double, name: mount-double, subPath: mount-double}
      restartPolicy: Never
      volumes:
      - name: mount-single
        persistentVolumeClaim:
          claimName: multimount
      - name: mount-double
        persistentVolumeClaim:
          claimName: multimount
```
